#!/bin/bash

# this script counts the number of gadgets in a binary, 
# excluding the ones generated by our tool, 
# which aren't useful

# uses ropper


# this is generated by the ret encryption pass
RET_ENCR_LEAVE="xor qword ptr [rsp], r11; ret;"

OUR_GADGETS="$RET_ENCR_LEAVE"

UNFILTERED=$(ropper --nocolor --file $1 | grep "0x")
UNFILTERED_COUNT=$(echo "$UNFILTERED" | wc -l)
FILTERED_COUNT=0
while read -r line; do
  while read -r gadget; do
    if [[ "$line" == *"$gadget"* ]]; then
      ((FILTERED_COUNT++))
      break
    fi
  done <<< "$OUR_GADGETS"
done <<< "$UNFILTERED"

echo "Unfiltered count: $UNFILTERED_COUNT"
echo "Filtered count: $FILTERED_COUNT"
echo "Number of \"useful\" gadgets: $((UNFILTERED_COUNT-FILTERED_COUNT))"
